Add documentation for firmware resiliency
slimbootloader/documentation pull request #151
Opened 2022-12-08 21:20 UTC by sean-m-mcginn

This change adds a section for firmware resiliency as well as updates existing sections that are related to firmware resiliency

Signed-off-by: Sean McGinn <sean.mcginn@intel.com>

2022-12-09 21:09 UTC, rprangar commented on source/security/firmware-resiliency-and-recovery.rst
> +|SPN| implements a resiliency and recovery mechanism for boot-critical firmware. This along with :ref:`firmware-update` make |SPN| compliant with NIST SP 800-193.
Regarding NIST compliancy - please remove that.

2022-12-09 21:49 UTC, rprangar commented on source/security/firmware-resiliency-and-recovery.rst
> +a normal boot to OS in executed, cancelling out a firmware update if one in flight. Thus, this can occur during a normal boot, or a update-related boot. So, the primary partition
a normal boot to OS *is* executed

2022-12-09 21:49 UTC, rprangar commented on source/security/firmware-resiliency-and-recovery.rst
> +a normal boot to OS in executed, cancelling out a firmware update if one in flight. Thus, this can occur during a normal boot, or a update-related boot. So, the primary partition
firmware update if one *is* in flight.

2022-12-14 14:52 UTC, rprangar approved these changes
LGTM

2022-12-14 22:13 UTC, lsubash requested changes

2022-12-14 22:13 UTC, lsubash commented on source/security/firmware-resiliency-and-recovery.rst
> +The diagram below shows the boot flow when a boot failure occurs on the primary boot partition.
We can add a block diagram for the resiliency feature and later go to the flow charts for detailed view.

2022-12-14 22:13 UTC, lsubash commented on source/security/firmware-update.rst
> -  * |SPN| image is designed to contain redundant boot components and depends on hardware assisted boot partition switch to support fail-safe update.
The descriptions on left side are required.

2022-12-14 22:13 UTC, lsubash commented on source/security/firmware-update.rst
> +  These firmware identifier strings should be followed by the assoicated binary path.
Limitations of the tool using redundant and non-redundant blocks at time is not supported any more

2022-12-14 22:13 UTC, lsubash commented on source/security/firmware-update.rst
Mention the default one used in CFG file

2022-12-14 22:13 UTC, lsubash commented on source/tools/index.rst
> +   UcodeUtility
Add a tutorial section - Mentioned about the tools to corrupt image at static and at run time.

2022-12-14 22:13 UTC, lsubash commented on source/security/firmware-resiliency-and-recovery.rst
> +The diagram below shows the boot flow when a boot failure occurs on the backup boot partition.
These diagrams need to be modified. We should capture two cases.
- Failure occured in Fwupdate
- Failure in primary boot partition.

2023-01-13 19:47 UTC, lsubash commented on source/security/firmware-update.rst
> -  For example, the following command generates a capsule image (``FwuImage.bin``) containing an IFWI image (``sbl.bios.bin``), CSME image (``csme.bin``), CSME Firmware Update Driver (``csme_fw_update
add example command for container component update as it gets removed in combination with Bios.

2023-01-13 19:47 UTC, lsubash commented on source/tutorials/ex_corrupt_sbl_component.rst
> +.. _ExerciseCorruptSblComponent:
Add a note for build PCD to enable this tool.

2023-01-13 19:47 UTC, lsubash commented on source/tutorials/ex_corrupt_sbl_component.rst
> +``CorruptComponentUtility.py`` corrupts an SBL component (e.g. an item from its flash map) in either
do mention not to include this tool in production.

2023-01-13 20:43 UTC, lsubash commented on source/tutorials/ex_corrupt_sbl_component.rst
> +.. _ExerciseCorruptSblComponent:
Thanks.

2023-01-13 20:43 UTC, lsubash commented on source/tutorials/ex_corrupt_sbl_component.rst
> +``CorruptComponentUtility.py`` corrupts an SBL component (e.g. an item from its flash map) in either
i am saying about shell tool.

2023-01-13 20:44 UTC, lsubash approved these changes
Looks good.

2023-01-13 20:49 UTC, lsubash commented
@sean-m-mcginn 
Remove WIP tag.

2023-01-13 21:17 UTC, kvparikh89 requested changes
Requesting changes to prevent merge till ADL-N is upstreamed

2023-01-13 21:39 UTC, kvparikh89 approved these changes

2023-01-13 21:40 UTC, merged